@startuml

'By Andreas Rovelt & Jonas Meinert Larsen

'Visuals
<style>
document {
  BackGroundColor grey
}
root {
  FontColor #?black:white
  LineColor black
}
</style>

'Sequence
Main -> Program
Program -> FileIO
FileIO -> Program
Program -> TextUI

loop
Program -> Register
Register -> Program
end loop

Program -> Login

Login -> DevMenu
DevMenu -> DevMenu
Login -> MainMenu
MainMenu -> MainMenu

MainMenu -> Program
DevMenu -> Program


@enduml